# Associations
# comment out the urls if you do not wish to display them
- # organization: PETA
  role: Huawei Certified ICT Associate-Artificial Intelligence (HCIA-AI) Certification, Huawei
  year: 24 Nov 2022 
  url: https://e.huawei.com/en/talent/#/cert/product-details?certifiedProductId=345&authenticationLevel=CTYPE_CARE_HCIA&technicalField=BSH
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.

- # organization: PETA
  role: Quantitative Text Analysis course, Essex University
  year: 6 Aug 2018 (2 weeks)
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.

- # organization: PETA
  role: The Doctoral Training Center (DTC) series, Swansea University, College of Science
  year: 2016 &mdash; 2017
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.


- # organization: PETA
  role: Train the Trainer Program, Saudi Aramco, 6-10 Oct 2012
  year: 6-10 Oct 2012
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.

- # organization: PETA
  role: The Instructor role towards vocational guidance, Development & training Centre (TVTC)
  year: 26-28 April 2008
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.

- # organization: PETA
  role: The tools of web pages development, HCT
  year: 12 – 19 Nov 2006
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.

- # organization: PETA
  role: Systems design and analysis, HCT
  year: 4-8 Nov 2006
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.

- # organization: PETA
  role: English, Computing Studies, and Technical Education program, Institute of technology in Christchurch, New Zealand
  year: 24 Aug 2005 (3 months)
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.

- # organization: PETA
  role: And many other sessions and workshops related to different disciplines
  # year: 24 Aug 2005 (3 months)
  # url: https://www.peta.org/
  # summary: Organized fund drives and participated in fundraising events for the benefit of PETA's local Springfield operations.
