- title: "Data Storytelling"
  organization: "Fractal Analytics"
  date: "15 June 2025"
  url: "https://www.coursera.org/learn/data-storytelling-fractal"

- title: "Creativity and Innovation"
  organization: "Colleges of Excellence (in cooperation with TVTC)"
  date: "1–5 December 2024"
  url: "https://lms.ic.edu.sa/ent/"

- title: "Data Visualization with Tableau Certificate"
  organization: "UC Davis - Coursera"
  date: "11 July 2024"
  url: "https://www.coursera.org/specializations/data-visualization"

- title: "Google Business Intelligence Certificate"
  organization: "Google - Coursera"
  date: "10 June 2024"
  url: "https://www.coursera.org/professional-certificates/google-business-intelligence"

- title: "Market Trends"
  organization: "Colleges of Excellence (in cooperation with TVTC)"
  date: "5–9 May 2024"
  url: "https://lms.ic.edu.sa/ent/"

- title: "Huawei Certified ICT Associate – Artificial Intelligence (HCIA-AI)"
  organization: "Huawei"
  date: "24 November 2022"
  url: "https://e.huawei.com/en/talent/#/cert/product-details?certifiedProductId=345&authenticationLevel=CTYPE_CARE_HCIA&technicalField=BSH"

- title: "Quantitative Text Analysis Course"
  organization: "University of Essex"
  date: "6 August 2018 (2 weeks)"

- title: "The Doctoral Training Center (DTC) Series"
  organization: "Swansea University, College of Science"
  date: "2016 — 2017"

- title: "Train the Trainer Program"
  organization: "Saudi Aramco"
  date: "6–10 October 2012"

- title: "The Instructor Role Towards Vocational Guidance"
  organization: "Development & Training Centre (TVTC)"
  date: "26–28 April 2008"

- title: "The Tools of Web Pages Development"
  organization: "HCT"
  date: "12–19 November 2006"

- title: "Systems Design and Analysis"
  organization: "HCT"
  date: "4–8 November 2006"

- title: "English, Computing Studies, and Technical Education Program"
  organization: "Institute of Technology, Christchurch, New Zealand"
  date: "24 August 2005 (3 months)"

- title: "Other workshops and sessions across various disciplines"
  organization: "Multiple institutions"
  # date: ""


